cd ~
l
ll
ls
cd AI
cd 1_math/
python3 1-1_Affine_Function_with_1feature 
python3 1-1_Affine_Function_with_1feature 
python3 1-1_Affine_Function_with_1feature.py 
python3 1-1_Affine_Function_with_1feature.py 
python3 1-1_Affine_Function_with_1feature.py 
python3 1-1_Affine_Function_with_1feature.py 
python3 1-1_Affine_Function_with_1feature.py 
python3 1-1_Affine_Function_with_1feature.py 
touch 1-1-1_Params_Initialization.py
python3 1-1-1_Params_Initialization.py 
python3 1-1-1_Params_Initialization.py 
python3 1-1-1_Params_Initialization.py 
touch 2-1_Affine_Functions_with_N_features.py
python3 2-1_Affine_Functions_with_N_features.py 
touch 1-3-1_Activation_Layers.py
python3 1-3-1_Activation_Layers.py 
python3 1-3-1_Activation_Layers.py 
touch 1-3-2_Activation_in_Dense_Layer.py
touch 1-4_Artificial_Neurons.py
touch 1-5-1_Shapes_of_Dense_Layer.py
python3 1-5-1_Shapes_of_Dense_Layer.py 
touch 1-5-2_Output_Calculations.py
python3 1-5-2
python3 1-5-2_Output_Calculations.py 
python3 1-5-2_Output_Calculations.py 
python3 1_math/3-1-1_The_Graphs_of_Odds_and_Logit.py 
cd 1_math/
python3 4-1-1_Dataset_for_Regression.py 
python3 4-1-1_Dataset_for_Regression.py 
python3 4-1-1_Dataset_for_Regression.py 
python 4-1-2_Dataset_for_Binary_Classification.py 
python 4-1-2_Dataset_for_Binary_Classification.py 
python 4-1-2_Dataset_for_Binary_Classification.py 
python 4-1-2_Dataset_for_Binary_Classification.py 
cd 1_math/
python3 4-1-3_Dataset_for_Multi-class_Classification.py 
python3 4-1-3_Dataset_for_Multi-class_Classification.py 
python3 4-1-3_Dataset_for_Multi-class_Classification.py 
python3 4-1-3_Dataset_for_Multi-class_Classification.py 
python3 4-1-3_Dataset_for_Multi-class_Classification.py 
cd 1_math/
python3 5-1-1_Shapes_of_Conv_Layers.py 
cd 1_math/
python3 5-2-2_Computations_with_Filters.py 
python3 5-2-2_Computations_with_Filters.py 
cd 1_math/
python3 6-4-1_ZeroPadding2D_Layer.py 
python3 6-4-1_ZeroPadding2D_Layer.py 
python3 7-1-1_Shapes_in_the_Feature_Extractors.py 
python3 7-1-1_Shapes_in_the_Feature_Extractors.py 
cd 1_math/
python 7-1-1_Implementation_with_Sequnial_Method.py 
python 7-1-1_Implementation_with_Sequnial_Method.py 
